### ISSUE TITLE
Gem version replacement may not be resilient to drift

### ISSUE THREAD

**Issue by mfurtak** [KrauseFx/nightly#2]
Where you have,

```ruby
File.write(version_path, File.read(version_path).gsub(previous_version.to_s, new_version))
```

I would be worried that if the version determined from RubyGems and the version in the repository are not the same, then the replacement will not happen properly.

Might it make sense to replace the version number in that file regardless of what version is currently in there? A regex might make that easier.

**Comment by KrauseFx** [comment]
Agreed, looking into this now 👍
